const DIFFICULTY = 1;
const MINE_RATE = 3000;
const DIFFICULTY_ADJUSTMENT_INTERVAL = 3;
const NUM_WORKERS = 8;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  DIFFICULTY_ADJUSTMENT_INTERVAL,
  NUM_WORKERS,
};
