name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
    paths:
      - 'spletna-aplikacija-gama6/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: spletna-aplikacija-gama6
        push: true
        tags: mlukee/web-app:$(date +%s)
